### ISSUE TITLE
simple game saruman9/sui repository 404

### ISSUE THREAD

**Issue by kws1207** [saruman9/move_ctf_writeup#2]
In readme of simple game, it says to use `sui` repo and `move_ctf_2022` branch from https://github.com/saruman9/sui but it seems the repository is not accessible anymore.

Is there any alternative way?

**Comment by saruman9** [comment]
Unfortunately, there are no other options. I accidentally deleted the `sui` repository, completely forgetting that there is a branch with my changes. I tried to search for this fork on my old hdd/ssd, but unfortunately I didn't find anything.
